### PR TITLE
DM-11444: Use XXXXXXX as the end of the template string.

### PR DESCRIPTION
**Pull request by jdswinbank**

### CODE REVIEW

**Comment by jhoblitt** [comment]
@jdswinbank see the comment above the template

**Comment by jdswinbank** [comment]
Right — with this change, it warns but works:

```
::: Deploying Miniconda2-4.2.12-MacOSX-x86_64.sh                                          
######################################################################## 100.0%           
Please run using "bash" or "sh", but not "." or "source"                                  
/var/folders/jp/lqz3n0m17nqft7bwtw3b8n380000gp/T/Miniconda2-4.2.12-MacOSX-x86_64.sh.3EXXlcQI: line 18: return: can only `return' from a function or sourced script
PREFIX=/Users/jds/Projects/Astronomy/LSST/src/lsst/scripts/foo/python/miniconda2-4.2.12   
/var/folders/jp/lqz3n0m17nqft7bwtw3b8n380000gp/T/Miniconda2-4.2.12-MacOSX-x86_64.sh.3EXXlcQI: line 233: md5: command not found
WARNING: md5sum mismatch of tar archive                                                   
expected: 814be3efa81c38f3a6e9abc2eed93e85                                                
     got:                                                                                 
installing: python-2.7.12-1 ...                                                           
installing: conda-env-2.6.0-0 ...                                                         
```

Without this change, it fails entirely:

```
::: Deploying Miniconda2-4.2.12-MacOSX-x86_64.sh
mktemp: too few X's in template ‘XXXXXXXX.Miniconda2-4.2.12-MacOSX-x86_64.sh’
[jds@magpie (master *)]$ 
```

I don't _like_ the warning, but it beats dying completely.

**Comment by timj** [comment]
What's the deal with the warning about `md5` command being missing.

**Comment by jdswinbank** [comment]
That, I assume, is just my system:
```$ md5
bash: md5: command not found
```

**Comment by timj** [comment]
Aha. It's in `/sbin/` on my Mac.

**Comment by jhoblitt** [comment]
I can't figure out how to reproduce the `mktemp` error message:
```
jenkins-elcap-1:~ square$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1217
jenkins-elcap-1:~ square$ which mktemp
/usr/bin/mktemp
jenkins-elcap-1:~ square$ mktemp -t "XXXXXXXX.foo"
/var/folders/6w/b0_0rw6j1938_4y4k6v_hcc80000gn/T/XXXXXXXX.foo.2PuDhwf0

```

**Comment by jhoblitt** [comment]
Also works on sierra for me:

```
jenkins-sierra-1:~ square$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
jenkins-sierra-1:~ square$ which mktemp
/usr/bin/mktemp
jenkins-sierra-1:~ square$ mktemp -t "XXXXXXXX.foo"
/var/folders/6w/b0_0rw6j1938_4y4k6v_hcc80000gn/T/XXXXXXXX.foo.bIXsYQlB

```

**Comment by jdswinbank** [comment]
Oh, that's ... weird:

```
[swinbank@tiger-sumire stack]$ echo mktemp -t XXXXX.${miniconda_file_name}
mktemp -t XXXXX.Miniconda2-4.2.12-MacOSX-x86_64.sh
[swinbank@tiger-sumire stack]$ mktemp -t "XXXXX.${miniconda_file_name}"
mktemp: too few X's in template `XXXXX.Miniconda2-4.2.12-MacOSX-x86_64.sh'
[swinbank@tiger-sumire stack]$ mktemp -t "XXXXX.foo"
/tmp/m8ybF.foo
[swinbank@tiger-sumire stack]$ mktemp -t "${miniconda_file_name}.XXXXX"
/tmp/Miniconda2-4.2.12-MacOSX-x86_64.sh.17KR8
[swinbank@tiger-sumire stack]$ uname -a
Linux tiger-sumire 2.6.32-696.3.2.el6.x86_64 #1 SMP Mon Jun 19 23:17:35 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jdswinbank** [comment]
Oh! It's because of the `MacOSX`. `mktemp` fixates on the _last_ `X` in the template.

**Comment by jhoblitt** [comment]
I can't reproduce that either.  Could you see if your binary matches mine?
```
jenkins-elcap-1:~ square$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1217
jenkins-elcap-1:~ square$ mktemp -t XXXXX.Miniconda2-4.2.12-MacOSX-x86_64.sh
/var/folders/6w/b0_0rw6j1938_4y4k6v_hcc80000gn/T/XXXXX.Miniconda2-4.2.12-MacOSX-x86_64.sh.niQvhnpa
jenkins-elcap-1:~ square$ md5 `which mktemp`
MD5 (/usr/bin/mktemp) = 7e5269e7b13e6396474826489231766c


jenkins-sierra-1:~ square$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
jenkins-sierra-1:~ square$  mktemp -t XXXXX.Miniconda2-4.2.12-MacOSX-x86_64.sh
/var/folders/6w/b0_0rw6j1938_4y4k6v_hcc80000gn/T/XXXXX.Miniconda2-4.2.12-MacOSX-x86_64.sh.fqVW3gKT
jenkins-sierra-1:~ square$ md5 `which mktemp`
MD5 (/usr/bin/mktemp) = 3606580530777b2e07e0c5d642a069c7
```

**Comment by jhoblitt** [comment]
@jdswinbank Why are you trying to install the osx build of miniconda on a linux box?

**Comment by jhoblitt** [comment]
OK - I can reproduce this failure with GNU `mktemp`:

```
[jhoblitt@drab ~]$ mktemp --version
mktemp (GNU coreutils) 8.27
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jim Meyering and Eric Blake.
[jhoblitt@drab ~]$ mktemp -t XXXXX.Miniconda2-4.2.12-MacOSX-x86_64.sh
mktemp: too few X's in template ‘XXXXX.Miniconda2-4.2.12-MacOSX-x86_64.sh’
```

**Comment by jhoblitt** [comment]
This is probably a sanity checking bug in GNU `mktemp`.  It works if you split the pattern and filename.

```
[jhoblitt@drab ~]$ mktemp -t XXXXX --suffix Miniconda2-4.2.12-MacOSX-x86_64.sh
/tmp/QX85uMiniconda2-4.2.12-MacOSX-x86_64.sh
```
There is no equivalent on OSX.

**Comment by jdswinbank** [comment]
> Why are you trying to install the osx build of miniconda on a linux box?

Well spotted. Actually, I was just dumping that into whichever terminal was closest for testing. However, is likely a GNU `mktemp` issue. I have:

```
[jds@magpie ~]$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.6
BuildVersion:   16G29
[jds@magpie ~]$ mktemp --version
mktemp (GNU coreutils) 8.27
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jim Meyering and Eric Blake.
```

**Comment by jhoblitt** [comment]
I'll try renaming newer versions of the miniconda installer to see what happens.  I have a feeling of deja vu about this.  We might be able to just remove Xs from the installer filename and not subject end users to the warning.

**Comment by jdswinbank** [comment]
Obsolete; see #59.

**Pull request closed without merging**
