### PR TITLE
assorted trivial fixes and style cleanups

### PR DESCRIPTION
**Pull request by jhoblitt**
Split out of #37

### CODE REVIEW

**Comment by timj** [comment]
I think the instructions tell people to run it as `bash newinstall.sh` 😄

**Comment by jhoblitt** [comment]
@athornton `==` is indeed a bashism but note that we're also using `[[ ]]`, which isn't POSIX either.

**Comment by jhoblitt** [comment]
I've tacked on some fixes to the "up2date" check so it does give an ugly error message when piping the script into the shell.  I'll wait for CI to pass again before merging.

**Comment by jhoblitt** [comment]
@athornton Brings up a good point about 80 cols.  That has been irritating me too.  I will add a reformatting commit.

**Comment by jhoblitt** [comment]
The "80cols" changeset gets almost every line <= 80 cols with a tabstop of 2.

**Comment by jhoblitt** [comment]
There is still a weird failure on osx that I don't fully understand but it seems to be caused by travis running the build from a non-login shell.  The rvm folks have a work around for it:

https://github.com/rvm/rvm/commit/cbc4488028ccc682a872034ba823f61bf2d9cf6d

However, I'm going to go ahead and merge this since I can't reproduce the failure by hand.

**Pull request merged**
